# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f9f31e87bdbe72f142a5eaff97805a8d0ff003c0a5db8c9a0a8664f51e77be66e48aa06a14b2b443b9fc793eaf14193f00c1a8e18f0334315b01ec6a28ac1e5

test:
  secret_key_base: 1d5d8c7792e7d309e39e20aa5d9602e83edc3a9713851088d05e812d1c88ca833ddea90e1aae06f0cfea8a6263d0a77aa2c873de3ad2552742edcbc38893ac04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
